### ISSUE TITLE
pkg_resources: NotImplementedError: Can't perform this operation for unregistered loader type

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunavut#144]
I tried upgrading to PyTest v5.3, but Nunavut stopped working when invoked by the testing suite:

```
NotImplementedError("Can't perform this operation for unregistered loader type")
Traceback (most recent call last):

  <...irrelevant...>

  File "/home/travis/build/UAVCAN/pyuavcan/pyuavcan/dsdl/_compiler.py", line 197, in generate_package
    namespace_output_stem='__init__')

  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/nunavut/lang/__init__.py", line 225, in __init__
    self._config = self._load_config(*additional_config_files)

  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/nunavut/lang/__init__.py", line 208, in _load_config
    resources = [r for r in pkg_resources.resource_listdir(__name__, '.') if r.endswith('.ini')]

  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1164, in resource_listdir
    resource_name

  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1442, in resource_listdir
    return self._listdir(self._fn(self.module_path, resource_name))

  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1484, in _listdir
    "Can't perform this operation for unregistered loader type"

NotImplementedError: Can't perform this operation for unregistered loader type
```

It's super weird that the exception comes from `pkg_resources`. It does not seem to be involved here at all.

Nunavut works fine outside of PyTest. I googled around a bit but could not find a quick solution, so I decided to downgrade back to PyTest v4.6 for now.

**Comment by thirtytwobits** [comment]
Is this still a thing? Nunavut has been using pytest >= 5.4.3 for about 10 months now?

**Comment by pavel-kirienko** [comment]
Yes, it is:

```text
UNEXPECTED EXCEPTION: NotImplementedError("Can't perform this operation for unregistered loader type")
Traceback (most recent call last):
  File "/usr/lib/python3.9/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest pyuavcan.dsdl._builtin_form.to_builtin[1]>", line 1, in <module>
  File "/home/pavel/uavcan/pyuavcan/tests/dsdl/conftest.py", line 55, in compile
    out = pyuavcan.dsdl.compile_all(
  File "/home/pavel/uavcan/pyuavcan/pyuavcan/dsdl/_compiler.py", line 302, in compile_all
    gpi = compile(
  File "/home/pavel/uavcan/pyuavcan/pyuavcan/dsdl/_compiler.py", line 187, in compile
    language_context = nunavut.lang.LanguageContext("py", namespace_output_stem="__init__")
  File "/home/pavel/uavcan/pyuavcan/.nox/test-3-9/lib/python3.9/site-packages/nunavut/lang/__init__.py", line 459, in __init__
    self._config = self._load_config(*additional_config_files)
  File "/home/pavel/uavcan/pyuavcan/.nox/test-3-9/lib/python3.9/site-packages/nunavut/lang/__init__.py", line 439, in _load_config
    resources = [r for r in pkg_resources.resource_listdir(__name__, '.') if r.endswith('.ini')]
  File "/home/pavel/uavcan/pyuavcan/.nox/test-3-9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1148, in resource_listdir
    return get_provider(package_or_requirement).resource_listdir(
  File "/home/pavel/uavcan/pyuavcan/.nox/test-3-9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1426, in resource_listdir
    return self._listdir(self._fn(self.module_path, resource_name))
  File "/home/pavel/uavcan/pyuavcan/.nox/test-3-9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1468, in _listdir
    raise NotImplementedError(
NotImplementedError: Can't perform this operation for unregistered loader type
/home/pavel/uavcan/pyuavcan/pyuavcan/dsdl/_builtin_form.py:28: UnexpectedException
```

**Comment by pavel-kirienko** [comment]
@thirtytwobits I would like to prioritize this. What would be the preferred way to address this? Switch to importlib?

```
/home/zubaxpc/.local/lib/python3.9/site-packages/nunavut/lang/__init__.py:70: in _load_config
    resources = [r for r in pkg_resources.resource_listdir(__name__, ".") if r.endswith(".yaml")]
```
